INSERT INTO cartitem (PRODUCT_ID, PRODUCT_NAME, QUANTITY, PRICE) VALUES ('101', 'Kayak', 1, 275) ON CONFLICT (PRODUCT_ID) DO NOTHING;
INSERT INTO cartitem (PRODUCT_ID, PRODUCT_NAME, QUANTITY, PRICE) VALUES ('102', 'Lifejacket', 1, 48.95) ON CONFLICT (PRODUCT_ID) DO NOTHING;
INSERT INTO cartitem (PRODUCT_ID, PRODUCT_NAME, QUANTITY, PRICE) VALUES ('103', 'Soccer Ball', 2, 19.50) ON CONFLICT (PRODUCT_ID) DO NOTHING;
INSERT INTO cartitem (PRODUCT_ID, PRODUCT_NAME, QUANTITY, PRICE) VALUES ('104', 'Corner Flags', 1, 34.95) ON CONFLICT (PRODUCT_ID) DO NOTHING;
