--CREATE DATABASE kingtan;

--\c kingtan;

CREATE TABLE IF NOT EXISTS cartitem (
  ID SERIAL PRIMARY KEY,
  PRODUCT_ID VARCHAR(45) NOT NULL UNIQUE,
  PRODUCT_NAME VARCHAR(45) NOT NULL UNIQUE,
  QUANTITY INTEGER NULL,
  PRICE DECIMAL(5,2) NULL);