spring:
  application:
    name: product
#  profiles:
#    active: dev

  data:
    mongodb:
      uri: mongodb://admin:hulun@localhost:27018/productdb?authSource=admin
#      uri: mongodb://queen:27018/productdb?authSource=admin
      database: productdb

  ########## Kafka ##########
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

########## Spring OpenAPI (Swagger) ##########
springdoc:
  api-docs:
    path: /api-docs  # Endpoint for OpenAPI JSON
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI endpoint

########## Server Port ##########
# server:
#   port: 8883

logging:
  level:
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.boot.context.config: DEBUG